---
engines:
  coffeelint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - "**.scss"
  - "**.coffee"
exclude_paths:
- "stylesheets/_reset.scss"
- "**.css"
- "stylesheets/content/_highlight-js.scss"
- "stylesheets/content/_pygment.scss"
